### ISSUE TITLE
cwebp: not found

### ISSUE THREAD

**Issue by waqasy** [randyjensen/rj-webp-converter#1]
Even though I've set the file permission to 744 but I still keep getting 

> ../plugins/rj-webp-converter-master/libs/libwebp-0.4.1-rc1-linux-x86-32/bin/cwebp: not found

**Comment by randyjensen** [comment]
Can you try setting it to 777 and see if that works? Don't leave it on that, but I'm not able to reproduce.

**Comment by waqasy** [comment]
I uploaded the plugin and the warning has vanished. Seems like ftp didn't upload the complete file. But again there are no webp images after uploading. Can you please mention which version of linux you're on?. I'm using 

> Ubuntu 16.04.2 LTS (GNU/Linux 4.8.6-x86_64-linode78 x86_64)

Ok. I downloaded 64bit library from google's [downloads repository](https://storage.googleapis.com/downloads.webmproject.org/releases/webp/index.html) now its working :100:

**Comment by randyjensen** [comment]
Glad you got it working!
